name: "Enforce Action Policy"
on:
  milestone:
    types:
      - created

jobs:
  enforce-package-policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "Check for action violations"
        id: action-policy
        with:
          policy: allow
          policy-url: "https://gist.githubusercontent.com/rob-derosa/ba7ecb82b164eca456142337acbdf6c0/raw/6713b441c33b892a15be53f959125a9f57324e41/actions_policy.json"
          fail-if-violations: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bad-actor/unstrusted-action@beta
      - uses: unapproved-author/very-cool-action@v6
        name: "Respond to action violations"
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          violations: ${{steps.action-policy.outputs.violations}}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/action_violation.js`)
            await script({github, context, core})

