name: "Enforce Action Policy"
on:
  push:
  pull_request:
    types:
      - opened
      - edited
jobs:
  enforce-action-policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: "Check for action violations"
        id: action-policy
        with:
          policy: prohibit
          policy-url: "https://gist.githubusercontent.com/rob-derosa/de2a366bd992e712837efa2e66148865/raw/37f9f6b24575dfb19efc2a76dc818ffdaf156864/prohibit_list.json"
          fail-if-violations: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/github-script@v2
        name: "Respond to action violations"
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          violations: ${{steps.action-policy.outputs.violations}}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/action_violation.js`)
            await script({github, context, core})
